name: server
description: An Aqueduct backend for Digital Trading Cards
version: 0.0.1
author: Ashvin <warrierar@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
